version: '3.1'

services:
  xMeetingScheduling:
    image: evecimar/laravel-5.6:alpine
    ports:
      - 8000:80
    volumes:
      - ../:/var/www/app
  mysql:
      image: mysql:5.7
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: qwe123
        MYSQL_DATABASE: xmeetingscheduling
  # redis:
  #     image: redis
  #     ports:
  #       - 6379:6379