version: '3.1'

services:
  xMeetingScheduling:
    image: evecimar/laravel-5.6:alpine
    ports:
      - 8000:80
    volumes:
      - ../:/var/www/app
    environment:
      APP_NAME: xMeetingScheduling
      APP_ENV: local
      APP_KEY: base64:7aRtV1HclDG8kUlpDvCKM9EC5on7NzGKieBx2nule4c=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      APP_TIMEZONE: America/Sao_Paulo

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: xmeetingscheduling
      DB_USERNAME: root
      DB_PASSWORD: qwe123

      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
  mysql:
      image: mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: qwe123
        MYSQL_DATABASE: xmeetingscheduling
  redis:
      image: redis
      ports:
        - 6379:6379